### ISSUE TITLE
cannot add nginx1 instance on Module 2 - Deploy the API Gateway instance

### ISSUE THREAD

**Issue by M1cHae1W0u9** [f5devcentral/f5-agility-labs-nginx#116]
follow the step 5 on Module 2 - Deploy the API Gateway instance, and add nginx1 instance with curl or wget, it will show error info <curl: (7) Failed connect to 10.1.20.4:443; Connection timed out>.

How to solve:
there is no subnet - 20 on NGINX-1 - API GW, create eth1 interface with following config
	[centos@e0df010e-8f28-4e80-9a90-3cbf714cbe9b ~]$ sudo vi /etc/sysconfig/network-scripts/ifcfg-eth1 
	# Created by cloud-init on instance boot automatically, do not edit.
	#
	BOOTPROTO=dhcp
	DEVICE=eth1
	HWADDR=52:54:00:6c:5e:f6
	ONBOOT=yes
	TYPE=Ethernet
	USERCTL=no

after doing this, restart this instance named NGINX-1 - API GW.

**Comment by MattDierick** [comment]
Good catch, fixing it !!!!! I had to resping 2 new centos and I forgot to add the 2nd interrace.

**Comment by MattDierick** [comment]
Fixed, in UDF BP Revision 26. Thanks for the head up.
