### ISSUE TITLE
add a step to export and download the openapi/swagger spec

### ISSUE THREAD

**Issue by bwolmarans** [f5devcentral/f5-agility-labs-nginx#230]
In https://github.com/f5devcentral/f5-agility-labs-nginx/blob/develop/docs/class10/module3/lab1/lab1.rst need to add a step to export and download the openapi/swagger spec so that it can be dragg'd and dropp'd

**Comment by MattDierick** [comment]
Brett, the student must not use NMS UI outside RDP Jumphost Win10, else nms.conf will be overwritten by public UDF proxy fqdn. And N+ will lose connectivity with NMS at next reboot (shutdown).

The swagger can be drag and dropped from the WIn Desktop10 Jumphost into the NMS UI.
