### ISSUE TITLE
topology diagram might need more details - like a dataplane LB and the dev portal server

### ISSUE THREAD

**Issue by bwolmarans** [f5devcentral/f5-agility-labs-nginx#232]
First, I believe there may already be plans for the following, but just wanted to track it here:  It is not clear to first look at the UDF blueprint components, and the lab steps like creating the api-cluster and dev-cluster and relate them to the topology diagram.  For example, and I am not sure about this, but it seems like the mobile user, should they not first be going to a (nginx+) load balancer data plane instance, and api.sentence.com should resolve to the load balancer ip?  Also on the topology diagram, because the dev portal is not shown, this seems confusing.  As an aside, I actually cannot find a good diagram of this on nginx docs site, the diagram on the ACM page is also confusing because it is a logical diagram shown only some of the logic, and there does not seem to be a topology diagram.

**Comment by MattDierick** [comment]
Good point Brett, I used an old diagram from the Controller v3 lab. Will create a new one with more details.

**Comment by bwolmarans** [comment]
https://i.imgur.com/DWPptmo.png

**Comment by bwolmarans** [comment]
updated image with ip addresses which will be helpful to network-centric SE audiences who need to learn to think not only of ip addresses, but also services and namespaces: https://i.imgur.com/FkIkZU3.png
