### ISSUE TITLE
docs: class 10 mod 3 step 4

### ISSUE THREAD

**Issue by bwolmarans** [f5devcentral/f5-agility-labs-nginx#236]
This sentence should probably be removed: "As you can notice, Infra team and API team have their own and separated workspace" because there is not a infra team and api team workspace

**Comment by MattDierick** [comment]
correct, wrong term. I don't know how we call the Infra and Service icons. Need to think about it. It is tied to the segregation.

**Comment by russgmoore** [comment]
This appears to be resolved for multiple reasons.
