### ISSUE TITLE
docs: class 10 mod 4 step 7

### ISSUE THREAD

**Issue by bwolmarans** [f5devcentral/f5-agility-labs-nginx#237]
Because it is easy for the student to accidently to this in the CORS dropdown instead of where they really need to do it in the OPTIONS dropdown, I suggest change "And add the header apikey into the allow list. Scroll down till the end, and then in the field enter apikey and click Add Header" to "In the OPTIONS field, add the header apikey into the allow list. Scroll down till the end, and then in the field enter apikey and click Add Header"

**Comment by russgmoore** [comment]
Moving to closed
