### ISSUE TITLE
2 typos - Class 10 Mod 7 Step 13

### ISSUE THREAD

**Issue by parkinglot837** [f5devcentral/f5-agility-labs-nginx#238]
https://clouddocs.f5.com/training/community/nginx/html/class10/module7/lab3/lab3.html

The word "valid" is misspelled twice.  

1.  But in this use case, the API GW does not check against Keycloak is the JWT token is **_valide_**.
2. OAuthv2 Introspect adds a capability for the API GW to check against the Oauth AS (Keycloak) if the JWT is **_valide_**

And that 2nd sentence needs a period "." at the end.

Thanks

**Comment by russgmoore** [comment]
Moving to closed.
