### ISSUE TITLE
Cant install agent on N+ for APIGW or DevPortal

### ISSUE THREAD

**Issue by halimfaf** [f5devcentral/f5-agility-labs-nginx#289]
failed when trying to connect to pkgs.nginx.com. 

root@ubuntu:/# curl -k https://10.1.1.6/install/nginx-agent > install.sh && sudo sh install.sh -g devportal-cluster && sudo systemctl start nginx-agent
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44481    0 44481    0     0  3619k      0 --:--:-- --:--:-- --:--:-- 3619k
Overriding instance_group value from command line: devportal-cluster ...
Sudo permissions detected
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

********
Warning: An insecure connection will be used during this nginx-agent installation
********

ubuntu-20 

Adding public key https://10.1.1.6/packages-repository/nginx-signing.key...
Finished adding public key.
Adding NGINX Agent apt repository...
Creating apt config: /etc/apt/apt.conf.d/80agent
Adding nginx-agent.list to /etc/apt/sources.list.d 
Adding packages URL to /etc/apt/sources.list.d/nginx-agent.list
Updating permissions for /etc/apt/sources.list.d/nginx-agent.list to 644 
Public key to repository added.
Hit:1 https://10.1.1.6/packages-repository/deb/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease                                               
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                                
Err:5 https://pkgs.nginx.com/app-protect-security-updates/ubuntu focal InRelease                                  
  400  Bad Request [IP: 3.126.134.177 443]
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2338 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]                             
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2734 kB]                             
Err:9 https://pkgs.nginx.com/app-protect/ubuntu focal InRelease                        
  400  Bad Request [IP: 3.126.134.177 443]
Err:10 https://pkgs.nginx.com/plus/ubuntu focal InRelease                                                         
  400  Bad Request [IP: 3.126.134.177 443]
Get:11 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [453 kB]                                  
Get:12 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [16.9 kB]                                           
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2143 kB]                                        
Get:14 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [370 kB]                                          
Get:15 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [13.0 kB]                                                     
Get:16 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2031 kB]                                                      
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [300 kB]                                                  
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [576 B]                                                 
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1091 kB]                                        
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [260 kB]                                                   
Get:21 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [285 kB]                                                                    
Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [576 B]                                                                   
Get:23 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [864 kB]                                                         
Get:24 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [180 kB]                                                                  
Get:25 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [18.8 kB]                                                                  
Get:26 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [23.6 kB]                                          
Get:27 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [25.3 kB]                                 
Err:28 https://pkgs.nginx.com/nms/ubuntu focal InRelease                                                                                  
  400  Bad Request [IP: 3.126.134.177 443]
Get:29 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [5504 B]                                                   
Get:30 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [25.8 kB]                                                   
Get:31 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [7484 B]                                             
Get:32 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [620 B]                                     
Get:33 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [548 B]                     
Err:34 https://pkgs.nginx.com/adm/ubuntu focal InRelease                                                     
  400  Bad Request [IP: 3.126.134.177 443]
Reading package lists... Done                   
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'https://pkgs.nginx.com/app-protect-security-updates/ubuntu focal InRelease' is no longer signed.
E: Failed to fetch https://pkgs.nginx.com/app-protect-security-updates/ubuntu/dists/focal/InRelease  400  Bad Request [IP: 3.126.134.177 443]
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'https://pkgs.nginx.com/app-protect/ubuntu focal InRelease' is no longer signed.
E: Failed to fetch https://pkgs.nginx.com/app-protect/ubuntu/dists/focal/InRelease  400  Bad Request [IP: 3.126.134.177 443]
N: See apt-secure(8) manpage for repository creation and user configuration details.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
E: The repository 'https://pkgs.nginx.com/plus/ubuntu focal InRelease' is no longer signed.
E: Failed to fetch https://pkgs.nginx.com/plus/ubuntu/dists/focal/InRelease  400  Bad Request [IP: 3.126.134.177 443]
E: Failed to fetch https://pkgs.nginx.com/nms/ubuntu/dists/focal/InRelease  400  Bad Request [IP: 3.126.134.177 443]
E: The repository 'https://pkgs.nginx.com/nms/ubuntu focal InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://pkgs.nginx.com/adm/ubuntu/dists/focal/InRelease  400  Bad Request [IP: 3.126.134.177 443]
E: The repository 'https://pkgs.nginx.com/adm/ubuntu focal InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by halimfaf** [comment]
solved after updating nginx+ license in /etc/ssl/nginx

appreciate your help to update the license in main blueprint

**Comment by russgmoore** [comment]
Thank you for the update, moving to closed.
